#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="dokku/$APP";

echo "-----> Setting up JVM Args"
id=$(docker run --rm -e JAVA_OPTS='-Xms389m -Xmx512m' $IMAGE)
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
echo "-----> Setting JVM Args Complete"
